lib/recake_web/router.ex
defmodule RecakeWeb.Router do
  use RecakeWeb, :router

  import RecakeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :minimal_layout do
    plug :put_layout, {RecakeWeb.LayoutView, :minimal}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  # scope "/api", RecakeWeb do
  #   pipe_through :api
  # end

  scope "/", RecakeWeb do
    pipe_through [:browser, :minimal_layout, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", RecakeWeb do
    pipe_through [:browser, :require_authenticated_user]

    delete "/users/logout", UserSessionController, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    get "/", InboxController, :index
    post "/requests/:id/resolve", InboxController, :resolve
    put "/requests/:id", JobRequestController, :update

    resources "/jobs", JobController, except: [:show, :delete]
  end

  scope "/admin", RecakeWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_user]

    resources "/invitations", InvitationController, only: [:index, :create]
  end

  scope "/", RecakeWeb do
    pipe_through [:browser, :minimal_layout]

    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RecakeWeb.Telemetry
    end
  end
end

lib/recake_web/controllers/inbox_controller.ex
defmodule RecakeWeb.InboxController do
  use RecakeWeb, :controller

  alias Recake.Jobs

  def index(conn, _params) do
    # rename incoming_requests
    incoming_requests = Jobs.list_user_incoming_requests(conn.assigns.current_user)

    jobs =
      conn.assigns.current_user
      |> Jobs.list_user_jobs()
      |> Enum.map(&transform_recruits/1)

    render(conn, "index.html", incoming_requests: incoming_requests, jobs: jobs)
  end

  defp transform_recruits(job) do
    init = %{
      statistics: %{
        total: 0,
        available: %{
          total: 0,
          percent: 0
        },
        unavailable: %{
          total: 0,
          percent: 0
        },
        pending: %{
          total: 0,
          percent: 0
        }
      },
      available: [],
      hidden: []
    }

    requests =
      job.requests
      |> Enum.reduce(init, fn request, acc ->
        cond do
          request.state == "available" ->
            append_request_to(acc, request, :available, :available)

          request.state == "unavailable" ->
            append_request_to(acc, request, :hidden, :unavailable)

          request.state == "pending" ->
            append_request_to(acc, request, :hidden, :pending)
        end
        |> update_in([:statistics, :total], &(&1 + 1))
      end)
      |> (fn rs ->
            Enum.reduce([:available, :unavailable, :pending], rs, fn category, acc ->
              put_in(
                acc,
                [:statistics, category, :percent],
                round(get_in(acc, [:statistics, category, :total]) / acc.statistics.total * 100)
              )
            end)
          end).()
      |> (fn rs ->
            rs
            |> update_in([:available], &Enum.reverse/1)
            |> update_in([:hidden], &Enum.reverse/1)
          end).()

    %{job | requests: requests}
  end

  defp append_request_to(acc, request, group, stats_key) do
    acc
    |> update_in([group], &[request | &1])
    |> update_in([:statistics, stats_key, :total], &(&1 + 1))
  end
end

lib/recake_web/views/inbox_view.ex
defmodule RecakeWeb.InboxView do
  use RecakeWeb, :view

  import Phoenix.HTML
  import RecakeWeb.HtmlHelpers

  def request_acceptance_input(request) do
    display_recruit_count = request.job.recruit_count > 1

    classes =
      class_list([
        {"flex-1 py-2 text-green-500 border border-r-0 border-green-500 hover:bg-green-500 hover:text-white", true},
        {"rounded-l", !display_recruit_count},
      ])

    button =
      ~E"""
      <button name="available" class="<%= classes %>"><%= gettext("Show interest") %></button>
      """

    if display_recruit_count do
      ~E"""
        <div class="flex items-center bg-gray-700 rounded-l text-gray-200 text-lg px-2" data-tooltip="<%= gettext("How many recruits do you have available?") %>">
          <svg class="mr-1" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="20" height="20">
            <use href="#icon-user-plus" />
          </svg>
          <input type="number" name="recruit_count" min=1 max="<%= request.job.recruit_count %>" value=1 class="w-10 px-2 bg-gray-600 text-gray-100 font-bold text-right number-input-bare">
          <p class="ml-2">/<%= request.job.recruit_count %></p>
        </div>
        <%= button %>
      """
    else
      button
    end
  end

  def filter_requests(requests, state) when is_binary(state) do
    requests
    |> Enum.filter(& &1.state == state)
  end
  def filter_requests(requests, states) when is_list(states) do
    requests
    |> Enum.filter(& &1.state in states)
  end

  def request_status_badge(request) do
    {text, colors} =
      case request.state do
        "pending" -> {gettext("pending"), "bg-blue-200 text-blue-900"}
        "unavailable" -> {gettext("declined"), "bg-red-200 text-red-900"}

      end

    classes = "rounded text-sm px-2 mr-3 #{colors}"

    ~E"""
      <span class="<%= classes %>"><%= text %></span>
    """
  end
end

lib/recake_web/templates/inbox/index.html.eex
<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="display:none">
    <symbol viewBox="0 0 384 512" id="icon-location">
      <path fill="currentColor" d="M172.268 501.67C26.97 291.031 0 269.413 0 192 0 85.961 85.961 0 192 0s192 85.961 192 192c0 77.413-26.97 99.031-172.268 309.67-9.535 13.774-29.93 13.773-39.464 0zM192 272c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z"></path>
    </symbol>
    <symbol viewBox="0 0 576 512" id="icon-warning">
      <g class="fa-group"><path fill="currentColor" d="M569.52 440L329.58 24c-18.44-32-64.69-32-83.16 0L6.48 440c-18.42 31.94 4.64 72 41.57 72h479.89c36.87 0 60.06-40 41.58-72zM288 448a32 32 0 1 1 32-32 32 32 0 0 1-32 32zm38.24-238.41l-12.8 128A16 16 0 0 1 297.52 352h-19a16 16 0 0 1-15.92-14.41l-12.8-128A16 16 0 0 1 265.68 192h44.64a16 16 0 0 1 15.92 17.59z" opacity="0.4"></path><path fill="currentColor" d="M310.32 192h-44.64a16 16 0 0 0-15.92 17.59l12.8 128A16 16 0 0 0 278.48 352h19a16 16 0 0 0 15.92-14.41l12.8-128A16 16 0 0 0 310.32 192zM288 384a32 32 0 1 0 32 32 32 32 0 0 0-32-32z"></path></g>
    </symbol>
    <symbol viewBox="0 0 640 512" id="icon-user-plus">
      <path fill="currentColor" d="M624 208h-64v-64c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v64h-64c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h64v64c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16v-64h64c8.8 0 16-7.2 16-16v-32c0-8.8-7.2-16-16-16zm-400 48c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"></path>
    </symbol>
</svg>

<div class="pt-4 sm:pt-12">
  <%= render_alert(@conn, :success) %>
  <%= render_alert(@conn, :info) %>

  <div class="flex flex-col sm:flex-row space-y-16 sm:space-y-0 sm:space-x-16 lg:space-x-32">
    <div class="flex-1">
      <div class="flex items-center">
        <svg class="text-white bg-blue-500 flex items-center justify-center p-2 rounded-lg" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 576 512"><path fill="currentColor" d="M567.938 243.908L462.25 85.374A48.003 48.003 0 0 0 422.311 64H153.689a48 48 0 0 0-39.938 21.374L8.062 243.908A47.994 47.994 0 0 0 0 270.533V400c0 26.51 21.49 48 48 48h480c26.51 0 48-21.49 48-48V270.533a47.994 47.994 0 0 0-8.062-26.625zM162.252 128h251.497l85.333 128H376l-32 64H232l-32-64H76.918l85.334-128z"></path></svg>
        <p class="ml-4 text-lg">
          <%= gettext("Inbox") %>
        </p>
      </div>

      <%= if Enum.empty?(@incoming_requests) do %>
        <h2 class="my-6 bg-gray-200 p-2 text-center text-base text-gray-600 italic"><%= gettext "empty inbox" %></h2>
      <% else %>


      <div class="mt-6 space-y-4">
        <%= for request <- @incoming_requests do %>
        <div class="card p-0 flex flex-col" id="req-<%= request.id %>">
          <div class="p-4 border-b flex-1">
            <div class="flex justify-between">
              <h3 class="text-lg font-bold text-gray-800">
                <%= request.job.user.company %>
              </h3>
              <p class="text-gray-600 text-sm">
                <%= Timex.format!(request.inserted_at, "{relative}", :relative) %>
              </p>
            </div>
            <p class="text-gray-600 text-sm -mt-1"><%= gettext("org. nr") %>: <%= request.job.user.organization_number %></p>

            <%= if request.job.id06_required do %>
            <div class="mt-2 mb-3 flex justify-between text-base text-yellow-800 id06-warning">
              <p class="flex items-center">
                <svg class="text-yellow-600 mr-1" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="20" height="20">
                  <use href="#icon-warning" />
                </svg>
                <%= gettext("ID06 is required") %>
              </p>
            </div>
            <% end %>

            <p class="mt-2 text-gray-700">
              <%= request.job.description %>
            </p>
            <div class="mt-4 flex justify-between">
              <p class="flex items-center">
                <svg class="text-blue-500 mr-1" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="16" height="16">
                  <use href="#icon-location" />
                </svg>
                <%= request.job.location %>
              </p>
            </div>
          </div>

          <%= form_for @conn, Routes.job_request_path(@conn, :update, request), [class: "flex p-4", method: :put], fn _f -> %>
            <%= request_acceptance_input(request) %>
            <button name="unavailable" class="flex-1 py-2 text-red-500 border border-red-500 hover:bg-red-500 hover:text-white rounded-r"><%= gettext("No thanks") %></button>
          <% end %>

        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="flex-1">
      <div class="flex justify-between">
        <div class="flex items-center">
          <svg class="text-white bg-blue-500 flex items-center justify-center p-1 rounded-lg" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 640 512"><g class="fa-group"><path class="fa-secondary" fill="currentColor" d="M96 224a64 64 0 1 0-64-64 64.06 64.06 0 0 0 64 64zm480 32h-64a63.81 63.81 0 0 0-45.1 18.6A146.27 146.27 0 0 1 542 384h66a32 32 0 0 0 32-32v-32a64.06 64.06 0 0 0-64-64zm-512 0a64.06 64.06 0 0 0-64 64v32a32 32 0 0 0 32 32h65.9a146.64 146.64 0 0 1 75.2-109.4A63.81 63.81 0 0 0 128 256zm480-32a64 64 0 1 0-64-64 64.06 64.06 0 0 0 64 64z" opacity="0.4"></path><path class="fa-primary" fill="currentColor" d="M396.8 288h-8.3a157.53 157.53 0 0 1-68.5 16c-24.6 0-47.6-6-68.5-16h-8.3A115.23 115.23 0 0 0 128 403.2V432a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48v-28.8A115.23 115.23 0 0 0 396.8 288zM320 256a112 112 0 1 0-112-112 111.94 111.94 0 0 0 112 112z"></path></g></svg>
          <p class="ml-4 text-lg">
            <%= gettext("Workforce") %>
          </p>
        </div>

        <%= link to: Routes.job_path(@conn, :new), class: "flex items-center btn btn-small btn-success" do %>
          <svg aria-hidden="true" width="16" class="mr-2" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">><path fill="currentColor" d="M384 240v32c0 6.6-5.4 12-12 12h-88v88c0 6.6-5.4 12-12 12h-32c-6.6 0-12-5.4-12-12v-88h-88c-6.6 0-12-5.4-12-12v-32c0-6.6 5.4-12 12-12h88v-88c0-6.6 5.4-12 12-12h32c6.6 0 12 5.4 12 12v88h88c6.6 0 12 5.4 12 12zm120 16c0 137-111 248-248 248S8 393 8 256 119 8 256 8s248 111 248 248zm-48 0c0-110.5-89.5-200-200-200S56 145.5 56 256s89.5 200 200 200 200-89.5 200-200z"></path></svg>
          <%= gettext("Create request") %>
        <% end %>
      </div>

      <%= if Enum.empty?(@jobs) do %>
        <h2 class="my-6 bg-gray-200 p-2 text-center text-base text-gray-600 italic"><%= gettext "empty recruitments" %></h2>
      <% else %>
      <div class="mt-6 space-y-4">
        <%= for job <- @jobs do %>
        <div class="job card p-4">
          <div class="flex justify-between items-center">
            <div>
              <p class="text-xs text-gray-600 -mb-1"><%= readable_datetime(job.inserted_at) %></p>
              <p class="text-lg"><%= job.internal_id %></p>
            </div>
            <%= link to: Routes.job_path(@conn, :edit, job), class: "text-base" do %>
              <i class="fas fa-edit mr-1 text-blue-300"></i><%= gettext("Edit") %>
            <% end %>
          </div>

          <div class="mt-2">
            <p class="text-xs text-right text-gray-700"><%= {:safe, ngettext("%{count} sent request", "%{count} sent", job.requests.statistics.total)} %></p>
            <div class="bg-gray-300 h-2 rounded-full flex justify-full">
              <%= if job.requests.statistics.available.total > 0 do %>
                <div class="progress-bar-segment bg-green-400" style="width: <%= job.requests.statistics.available.percent %>%" data-tooltip="<%= job.requests.statistics.available.total %>"></div>
              <% end %>
              <%= if job.requests.statistics.unavailable.total > 0 do %>
                <div class="progress-bar-segment bg-red-400" style="width: <%= job.requests.statistics.unavailable.percent %>%" data-tooltip="<%= job.requests.statistics.unavailable.total %>"></div>
              <% end %>
            </div>
            <div class="mt-2 flex space-x-6 text-xs text-gray-600">

              <p class="flex items-center">
                <span class="bg-green-400 h-2 w-2 inline-block rounded-full mr-1"></span>
                <%= gettext("Available") %>
              </p>
              <p class="flex items-center">
                <span class="bg-red-400 h-2 w-2 inline-block rounded-full mr-1"></span>
                <%= gettext("Unavailable") %>
              </p>
              <p class="flex items-center">
                <span class="bg-gray-300 h-2 w-2 inline-block rounded-full mr-1"></span>
                <%= gettext("Pending") %>
              </p>
            </div>
          </div>

          <h4 class="text-gray-600 mt-6"><%= gettext("Available") %></h4>
          <div class="active-recruits space-y-4">
            <%= for request <- job.requests.available do %>
            <div class="hover:bg-gray-100 focus-within:bg-gray-100 p-4 rounded">
              <p class="text-lg text-gray-800">
                <%= request.recipient.company %>
              </p>
              <p class="text-sm text-gray-600 -mt-1">
                <%= gettext("org. nr") %>: <%= request.recipient.organization_number %>
              </p>

              <%= if job.recruit_count > 1 do %>
              <div class="flex mt-2 text-gray-700">
                <svg class="mr-2 text-gray-600" aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="20" height="20">
                  <use href="#icon-user-plus" />
                </svg>
                <%= request.recruit_count %> / <%= job.recruit_count %>
              </div>
              <% end %>

              <div class="pl-1">
                <p class="text-gray-700 mt-1 -mb-1">
                  <%= request.recipient.contact_name %>
                </p>
                <div class="flex items-baseline flex-wrap">
                  <p class="text-2xl mr-8 break-all">
                    <a href="tel:<%= request.recipient.phone %>"><%= request.recipient.phone %></a>
                  </p>
                  <p class="break-all">
                    <a href="mailto:<%= request.recipient.email %>"><%= request.recipient.email %></a>
                  </p>
                </div>
              </div>

            </div>
            <% end %>
          </div>
          <details class="inactive-recruits mt-8">
            <summary class="text-gray-600"><%= gettext("Other") %></summary>

            <%= for request <- job.requests.hidden do %>
            <p class="mt-2">
              <%= request_status_badge(request) %>
              <%= request.recipient.company %>
            </p>
            <% end %>
          </details>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>