lib/recake_web/router.ex
defmodule RecakeWeb.Router do
  use RecakeWeb, :router

  import RecakeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :minimal_layout do
    plug :put_layout, {RecakeWeb.LayoutView, :minimal}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  # scope "/api", RecakeWeb do
  #   pipe_through :api
  # end

  scope "/", RecakeWeb do
    pipe_through [:browser, :minimal_layout, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", RecakeWeb do
    pipe_through [:browser, :require_authenticated_user]

    delete "/users/logout", UserSessionController, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    get "/", InboxController, :index
    post "/requests/:id/resolve", InboxController, :resolve
    put "/requests/:id", JobRequestController, :update

    resources "/jobs", JobController, except: [:show, :delete]
  end

  scope "/admin", RecakeWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_user]

    resources "/invitations", InvitationController, only: [:index, :create]
  end

  scope "/", RecakeWeb do
    pipe_through [:browser, :minimal_layout]

    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RecakeWeb.Telemetry
    end
  end
end

lib/recake_web/controllers/user_session_controller.ex
defmodule RecakeWeb.UserSessionController do
  use RecakeWeb, :controller

  alias Recake.Accounts
  alias RecakeWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.login_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: gettext("Invalid e-mail or password"))
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:success, gettext("Logged out successfully"))
    |> UserAuth.logout_user()
  end
end

lib/recake_web/views/user_session_view.ex
defmodule RecakeWeb.UserSessionView do
  use RecakeWeb, :view


end

lib/recake_web/templates/user_session/new.html.eex
<h1 class="text-blue-700 text-xl text-center mb-6"><%= gettext "Login" %></h1>

<%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user], fn f -> %>
  <%= if @error_message do %>
    <div class="alert alert-error -mr-4 -ml-4 mb-4">
      <p><%= @error_message %></p>
    </div>
  <% end %>
  <%= render_alert(@conn, :info) %>
  <%= render_alert(@conn, :error) %>
  <%= render_alert(@conn, :success) %>

  <%= Form.text_input f, :email, label: gettext("Email") %>
  <%= Form.password_input f, :password, label: gettext("Password") %>
  <%= Form.checkbox f, :remember_me, label: gettext("Remember me") %>
  <%= Form.submit gettext("Login"), class: "w-full" %>
<% end %>

<!--
<div class="mt-12 text-center">
  <p><%= link gettext("Forgot password?"), to: Routes.user_reset_password_path(@conn, :new) %></p>
  <p class="text-gray-600"><%= gettext "Not a member?" %> <%= link gettext("Create account"), to: Routes.user_registration_path(@conn, :new) %></p>
</div>
-->