lib/recake_web/router.ex
defmodule RecakeWeb.Router do
  use RecakeWeb, :router

  import RecakeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :minimal_layout do
    plug :put_layout, {RecakeWeb.LayoutView, :minimal}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  # scope "/api", RecakeWeb do
  #   pipe_through :api
  # end

  scope "/", RecakeWeb do
    pipe_through [:browser, :minimal_layout, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", RecakeWeb do
    pipe_through [:browser, :require_authenticated_user]

    delete "/users/logout", UserSessionController, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    get "/", InboxController, :index
    post "/requests/:id/resolve", InboxController, :resolve
    put "/requests/:id", JobRequestController, :update

    resources "/jobs", JobController, except: [:show, :delete]
  end

  scope "/admin", RecakeWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_user]

    resources "/invitations", InvitationController, only: [:index, :create]
  end

  scope "/", RecakeWeb do
    pipe_through [:browser, :minimal_layout]

    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RecakeWeb.Telemetry
    end
  end
end

lib/recake_web/views/layout_view.ex
defmodule RecakeWeb.LayoutView do
  use RecakeWeb, :view

  import Phoenix.HTML

  @nav_link_classes "px-6 py-2 bg-white text-blue-800 hover:bg-gray-200 hover:no-underline"

  def nav_link(label, opts) do
    classes = Keyword.get(opts, :class)

    classes =
      if classes do
        "#{classes} #{@nav_link_classes}"
      else
        @nav_link_classes
      end

    opts = Keyword.put(opts, :class, classes)

    ~E"""
      <%= link label, opts %>
    """
  end

  def render_with_permission(user, permission, do: block) do
    if Enum.member?(user.admin_permissions, permission) do
      block
    else
      {:safe, ""}
    end
  end
end

lib/recake_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="sv">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Recake" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body class="bg-app font-sans min-h-screen">
    <header class="text-gray-600">
      <section class="container mx-auto px-2">
        <nav role="navigation" class="flex justify-between pt-6">
          <div class="flex items-center space-x-4">
            <%= link to: Routes.inbox_path(@conn, :index), class: "flex mr-8 hover:no-underline text-blue-700 hover:text-blue-500 group" do %>
              <svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" width="32" style="color: #a43e01" class="transform group-hover:-rotate-45 transition ease-in-out duration-300 " viewBox="0 0 512 512"><g class="fa-group"><path class="fa-secondary" fill="currentColor" d="M510.37 254.78l-12.08-76.26a132.53 132.53 0 0 0-37.16-73l-54.76-54.7a132 132 0 0 0-72.7-37L257 1.62a131.88 131.88 0 0 0-80.52 12.76l-69.14 35.21a132.35 132.35 0 0 0-57.79 57.8l-35.1 68.88a132.63 132.63 0 0 0-12.82 80.94l12.08 76.28a132.56 132.56 0 0 0 37.16 72.95l54.76 54.75a132.12 132.12 0 0 0 72.7 37.05L255 510.38a132 132 0 0 0 80.52-12.75l69.11-35.21a132.35 132.35 0 0 0 57.79-57.8l35.1-68.87a132.72 132.72 0 0 0 12.85-80.97zM176 368a32 32 0 1 1 32-32 32 32 0 0 1-32 32zm32-160a32 32 0 1 1 32-32 32 32 0 0 1-32 32zm160 128a32 32 0 1 1 32-32 32 32 0 0 1-32 32z" opacity="0.4"></path><path class="fa-primary" fill="currentColor" d="M368 272a32 32 0 1 0 32 32 32 32 0 0 0-32-32zM208 144a32 32 0 1 0 32 32 32 32 0 0 0-32-32zm-32 160a32 32 0 1 0 32 32 32 32 0 0 0-32-32z"></path></g></svg>
              <span class="text-xl font-bold ml-2 transition ease-in-out duration-300">Recake</p>
            <% end %>
          </div>
          <div class="cursor-pointer relative group" onclick="">
            <div class="py-2 px-4">
              <svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="16"><path fill="currentColor" d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.8 110c-17.9-15.4-38.5-27.3-60.8-35.1V25.8c0-5.6-3.9-10.5-9.4-11.7-36.7-8.2-74.3-7.8-109.2 0-5.5 1.2-9.4 6.1-9.4 11.7V75c-22.2 7.9-42.8 19.8-60.8 35.1L88.7 85.5c-4.9-2.8-11-1.9-14.8 2.3-24.7 26.7-43.6 58.9-54.7 94.6-1.7 5.4.6 11.2 5.5 14L67.3 221c-4.3 23.2-4.3 47 0 70.2l-42.6 24.6c-4.9 2.8-7.1 8.6-5.5 14 11.1 35.6 30 67.8 54.7 94.6 3.8 4.1 10 5.1 14.8 2.3l42.6-24.6c17.9 15.4 38.5 27.3 60.8 35.1v49.2c0 5.6 3.9 10.5 9.4 11.7 36.7 8.2 74.3 7.8 109.2 0 5.5-1.2 9.4-6.1 9.4-11.7v-49.2c22.2-7.9 42.8-19.8 60.8-35.1l42.6 24.6c4.9 2.8 11 1.9 14.8-2.3 24.7-26.7 43.6-58.9 54.7-94.6 1.5-5.5-.7-11.3-5.6-14.1zM256 336c-44.1 0-80-35.9-80-80s35.9-80 80-80 80 35.9 80 80-35.9 80-80 80z"></path></svg>
            </div>
            <div class="absolute hidden group-hover:flex flex-col shadow border-t-4 border-blue-600 right-0 whitespace-no-wrap">
              <%= render_with_permission @conn.assigns.current_user, "invitations" do %>
                <%= nav_link gettext("Invitations"), to: Routes.admin_invitation_path(@conn, :index), class: "admin-link" %>
              <% end %>
              <%= nav_link gettext("Settings"), to: Routes.user_settings_path(@conn, :edit) %>
              <%= nav_link gettext("Logout"), to: Routes.user_session_path(@conn, :delete), method: :delete %>
            </div>
          </div>
        </nav>
      </section>
    </header>
    <main role="main" class="container mx-auto px-2 pb-4 mt-4 sm:mt-12">
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/recake_web/templates/layout/minimal.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Recake" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body class="bg-app font-sans flex justify-center items-center h-screen">
    <main role="main" class="bg-white p-10 w-full max-w-md mx-2 shadow-lg rounded-lg border-t-8 border-blue-500">
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>